### ISSUE TITLE
Does it support php 8.2 ?

### ISSUE THREAD

**Issue by hgati** [integer-net/magento2-configurable-wysiwyg#4]
Does it support php 8.2 ?

**Comment by schmengler** [comment]
We did not test it yet, do you want to give it a try with https://github.com/PHPCompatibility/PHPCompatibility ?

**Comment by hgati** [comment]
> We did not test it yet, do you want to give it a try with https://github.com/PHPCompatibility/PHPCompatibility ?

I have simply created a my custom module and using it. 

I just tested on Magento 2.4.6 with PHP 8.2.24 after forking your module, and there don't seem to be any compatibility issues or errors. However, despite saving the settings, there is no change observed.

![](https://i.ibb.co/QdmN3KB/t1.png)

![](https://i.ibb.co/bbmpVBf/t2.png)

I will simply continue to use my module. :)
